
node:
  nodeSelector:
    node.cloudprovider.kubernetes.io/platform: nocloud

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule

storageClass:
  - name: proxmox-data-xfs
    storageID: data
    reclaimPolicy: Delete
    fstype: xfs
