apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "proxmox-csi-plugin.fullname" . }}-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "proxmox-csi-plugin.fullname" . }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "proxmox-csi-plugin.serviceAccountName" . }}-controller
    namespace: {{ .Release.Namespace }}
