{{- range $storage := .Values.storageClass }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $storage.name }}
provisioner: csi.proxmox.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: {{ default "Delete" $storage.reclaimPolicy }}
parameters:
  storageID: {{ $storage.storageID }}
  csi.storage.k8s.io/fstype: {{ default "ext4" $storage.fstype }}
---
{{- end }}
